### PR TITLE
Fix white-on-blue visibility issue

### LINKED ISSUE #5: Visibility issue: light foreground on blue Foam background
# The issue
By default, a light foreground color is chosen to be displayed on a blue background (in this variant, the blue is Foam `#9ccfd8`) in many console applications. This results in text that is almost unreadable in most cases, as illustrated in the examples below. This choice likely stems from the expectation that blue is usually a bit darker than green, leading to lighter foreground settings for the former and darker ones for the latter.

## Applying color theory
An analysis of the colors reveals that Pine actually contains more blue compared to Foam, even when normalized:
| Description | Pine | Foam |
| --- | --- | --- |
| HEX color | `#31748f` | `#9ccfd8` |
| Red | `0x31` or 49 | `0x9c` or 156 |
| Green | `0x74` or 116 | `0xcf` or 207 |
| Blue | `0x8f` or 143 | `0xd8` or 216 |
| Total intensity | 49 + 116 + 143 = 308 | 156 + 207 + 216 = 579 |
| Normalized Green | $`\frac{116}{308} \approx 0.377`$ | $`\frac{207}{579} \approx 0.358`$ |
| Normalized Blue | $`\frac{143}{308} \approx 0.464`$ | $`\frac{216}{579} \approx 0.373`$ |

While both Pine and Foam have more blue than green, Pine has slightly more blue in comparison. Coupled with the examples provided below, this leads to the suggestion that the blue and green colors should be swapped in this theme.

### Wifi-menu (with dialog)
[Wifi-menu](https://wiki.archlinux.org/title/Netctl) utilizes the widely-used [dialog](https://invisible-island.net/dialog/) library, which is nearly unreadable with the `regular2` color (blue) set to Foam `#9ccfd8`.

Before the changes
screenshot-2024-10-30-14-37-37

After the changes
screenshot-2024-10-30-14-36-46

### Taskwarrior colors output
By default, [Taskwarrior](https://taskwarrior.org/) does not change some foreground colors and instead falls back to whatever the terminal provides. The `blue` color in this example is what I'm referring to.

Before the changes
screenshot-2024-10-30-14-04-39

After the changes
screenshot-2024-10-30-14-16-58

## Solution
Swap the `regular2` and `regular4` colors (as well as their `bright` variants) as follows:
```ini
[color]
regular2 = 9ccfd8  # green (Foam)
regular4 = 31748f  # blue (Pine)
```

### PR DESCRIPTION
**Pull request by d2718nis**
Fixes #5

## Task list
- [ ] Ask the [foot](https://codeberg.org/dnkl/foot/src/branch/master/themes) maintainer to update the theme in the repository

### CODE REVIEW

**Comment by d2718nis** [comment]
Also I'm not sure whether the `-dawn` variant should also have its colors swapped for consistency. While this sounds plausible, I actually prefer the original (not swapped) colors:

`$ task color` before fix
taskwarrior-color-not-fixed-dawn

`$ task color` after fix
taskwarrior-color-fixed-dawn

`wifi-menu` before fix
wifi-menu-not-fixed-dawn

`wifi-menu` after fix
wifi-menu-fixed-dawn

**Comment by d2718nis** [comment]
Also fixed the indentation of the comments in each theme for consistency.

**Comment by d2718nis** [comment]
@EuCaue once you give your approval on swapping the `-dawn` theme variant colors as well, I'll push one more commit and it can be merged after that if everything else is OK.

**Comment by EuCaue** [comment]
Hey! Thanks for awesome work! =D
Sorry for the late response, busy with uni stuff. :p

Thanks for improving the colors!

I agree with you, the `-dawn` variant should be changed for consistency.

Let me know when it's ready to merge! =)

**Comment by d2718nis** [comment]
Sure, no problem! :+1:

You can merge this PR now — I’ve pushed everything needed. I also fixed the incorrect Pine color value in the dawn theme variant mentioned in [this comment](https://github.com/EuCaue/foot/issues/7#issuecomment-2453150428).

**Comment by EuCaue** [comment]
Thanks for all your work, will merge this now! :)

**Pull request merged**
