### PR TITLE
Add bright variants

### LINKED ISSUE #7: Provide a set of bright color variants
# The issue
In the current themes, most `bright` color variants are set to match the base colors. This limits the use of all 16 colors in the terminal color scheme, making it difficult to add accents or visual emphasis.
screenshot-2024-10-30-19-22-39

## Context
While the official Rose Pine [palette](https://rosepinetheme.com/palette/) provides only base colors, there’s potential to modify these by adjusting brightness and saturation. Since this palette leans toward muted tones, the following could be applied:
- **Brightness Shift**: To make colors "brighter", increase the RGB values of each color by about 10-20%, depending on the specific color to add a visible difference
- **Saturation Boost**: Some colors (like the red and yellow) benefit from a slight (around 10-15%) saturation increase to make them appear more vibrant

> The original specification only had 8 colors, and just gave them names. The SGR parameters 30–37 selected the foreground color, while 40–47 selected the background. Quite a few terminals implemented "bold" (SGR code 1) as a brighter color rather than a different font, thus providing 8 additional foreground colors.
[ANSI Escape Code](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit)

## Example
I didn't decide on the final result of how much should each of the `bright` variants add to its brightness and saturation to have a noticeable difference but at the same time maintain the overall theme aesthetics. Here's an example of how it could look for the main rose-pine theme:
screenshot-2024-10-30-19-44-01

Slightly brighter option
screenshot-2024-10-30-22-25-04

## Dependencies
I'm waiting for #6 to be merged to create a pull request for this feature.

### PR DESCRIPTION
**Pull request by d2718nis**
Fixes #7 

## Task list
- [ ] Ask the [foot](https://codeberg.org/dnkl/foot/src/branch/master/themes) maintainer to update the theme in the repository

### CODE REVIEW

**Comment by d2718nis** [comment]
I'll fix the conflict, one sec.

**Comment by d2718nis** [comment]
Done

**Comment by d2718nis** [comment]
I made slight updates to the colors and ultimately decided to adopt a more scientific approach by calculating the [CIE76](https://en.wikipedia.org/wiki/Color_difference#CIE76) color difference for each shade. While the visual differences may be minimal, this method ensures systematic reproducibility.

**Rose Pine**:
screenshot-2024-11-06-00-12-24

**Rose Pine Moon**:
screenshot-2024-11-06-00-12-34

**Rose Pine Dawn**:
screenshot-2024-11-06-00-12-43

**Comment by d2718nis** [comment]
@EuCaue added new 16-color themes into separate files. Also updated `readme.md` on new theme variants and refreshed the installation instructions. You can safely merge the changes if everything seems to be in place.

**Comment by d2718nis** [comment]
Hi @EuCaue! Hope everything is going well with your studies. Just wanted to check in on this pull request when you have a moment. I’ve implemented the changes we discussed in [this issue](https://github.com/EuCaue/foot/issues/7).

No rush if you’re still tied up with uni, but let me know if there’s anything else you’d like me to adjust. Thanks for your time, and looking forward to seeing this get merged.

**Comment by EuCaue** [comment]
Sorry for the late response! 😅

Thank you so much for your amazing contributions!! =D

Now it looks really good, because when people visit this repo, they have more options if they want to! =)

I truly appreciate all the effort!! 😄

**Pull request merged**
